ScientistWebsite.create(:id => 1, :name => "The Fletcher Lab", :url => "http://fletchlab.berkeley.edu/", :scientist_id => 23)
ScientistWebsite.create(:id => 2, :name => "MCB Profile", :url => "http://mcb.berkeley.edu/faculty/BMB/albert.html", :scientist_id => 3)
ScientistWebsite.create(:id => 3, :name => "Joint BioEnergy Institute", :url => "http://www.jbei.org/", :scientist_id => 1)
ScientistWebsite.create(:id => 4, :name => "The SIBYLS Beamline", :url => "http://bl1231.als.lbl.gov/", :scientist_id => 27)
ScientistWebsite.create(:id => 5, :name => "Anderson Lab", :url => "http://andersonlab.qb3.berkeley.edu/", :scientist_id => 4)
ScientistWebsite.create(:id => 6, :name => "The Blanch Lab", :url => "http://www.cchem.berkeley.edu/hwbgrp/", :scientist_id => 6)
ScientistWebsite.create(:id => 7, :name => "Joint BioEnergy Institute", :url => "http://www.jbei.org/", :scientist_id => 6)
ScientistWebsite.create(:id => 8, :name => "The SIBYLS Beamline", :url => "http://bl1231.als.lbl.gov/", :scientist_id => 16)
ScientistWebsite.create(:id => 11, :name => "Bustamante Lab", :url => "http://alice.berkeley.edu/", :scientist_id => 8)
ScientistWebsite.create(:id => 12, :name => "The Ginsberg Group", :url => "http://www.cchem.berkeley.edu/nsggrp/", :scientist_id => 25)
ScientistWebsite.create(:id => 13, :name => "The Fleming Group", :url => "http://www.cchem.berkeley.edu/grfgrp/", :scientist_id => 22)
ScientistWebsite.create(:id => 18, :name => "LBNL Advanced Light Source (ALS)", :url => "http://www-als.lbl.gov/", :scientist_id => 25)
ScientistWebsite.create(:id => 20, :name => "Joint BioEnergy Institute", :url => "http://www.jbei.org/", :scientist_id => 30)
ScientistWebsite.create(:id => 40, :name => "The Hammond Group", :url => "http://www.cchem.berkeley.edu/mchgrp/index.html", :scientist_id => 28)
ScientistWebsite.create(:id => 48, :name => "Chandler Group Research Page", :url => "http://gold.cchem.berkeley.edu/The_Chandler_Group/Home.html", :scientist_id => 10)
ScientistWebsite.create(:id => 49, :name => "JMC's Research Page", :url => "http://www.strgen.org/~jmc/", :scientist_id => 11)
ScientistWebsite.create(:id => 50, :name => "Structural Classification of Proteins (SCOP)", :url => "http://scop.berkeley.edu/", :scientist_id => 11)
ScientistWebsite.create(:id => 51, :name => "The Chang Group", :url => "http://www.cchem.berkeley.edu/mccgrp", :scientist_id => 12)
ScientistWebsite.create(:id => 52, :name => "Chu Group", :url => "http://www.cchem.berkeley.edu/chugrp/Welcome.html", :scientist_id => 14)
ScientistWebsite.create(:id => 53, :name => "ABEX", :url => "http://abex.lbl.gov/", :scientist_id => 17)
ScientistWebsite.create(:id => 54, :name => "Gavin E. Crooks", :url => "http://threeplusone.com/", :scientist_id => 18)
ScientistWebsite.create(:id => 58, :name => "metaMicrobesOnline", :url => "http://meta.microbesonline.org/", :scientist_id => 13)
ScientistWebsite.create(:id => 59, :name => "DOE Systems Biology Knowledgebase", :url => "http://kbase.science.energy.gov/", :scientist_id => 13)
ScientistWebsite.create(:id => 60, :name => "Computational and Theoretical Biology", :url => "http://pbd.lbl.gov/PBD/science/computational_theoretical_biology.html", :scientist_id => 5)
ScientistWebsite.create(:id => 61, :name => "Synthetic Biology", :url => "http://pbd.lbl.gov/PBD/science/synthetic_biology.html", :scientist_id => 5)
ScientistWebsite.create(:id => 62, :name => "Anderson Lab", :url => "http://andersonlab.qb3.berkeley.edu/", :scientist_id => 4)
