Scientist.create(:id => 24, :first_name => "Heinz", :last_name => "Frei", :picture => "hfrei0", :title => "Chemist Senior Scientist", :slug => "hfrei")
Scientist.create(:id => 6, :first_name => "Harvey", :last_name => "Blanch", :picture => "hblanch0", :title => "Chemical Sr Faculty Engineer", :slug => "hblanch")
Scientist.create(:id => 7, :first_name => "Steven", :last_name => "Brenner", :picture => "sbrenner0", :title => "Biologist Faculty Scientist", :slug => "sbrenner")
Scientist.create(:id => 5, :first_name => "Adam", :last_name => "Arkin", :picture => "aarkin0", :title => "Division Director", :slug => "aarkin")
Scientist.create(:id => 8, :first_name => "Carlos", :last_name => "Bustamante", :picture => "cbustamante0", :title => "Biophysicist Faculty Scientist", :slug => "cbustamante")
Scientist.create(:id => 19, :first_name => "Paramvir", :last_name => "Dehal", :picture => "pdehal0", :title => "Computational Research Scientist", :slug => "pdehal")
Scientist.create(:id => 20, :first_name => "Adam", :last_name => "Deutschbauer", :picture => "adeutschbauer0", :title => "Biologist Research Scientist", :slug => "adeutschbauer")
Scientist.create(:id => 21, :first_name => "Jennifer", :last_name => "Doudna", :picture => "jdoudna0", :title => "Biologist Faculty Scientist", :slug => "jdoudna")
Scientist.create(:id => 25, :first_name => "Naomi", :last_name => "Ginsberg", :picture => "nginsberg0", :title => "Faculty Scientist", :slug => "nginsberg")
Scientist.create(:id => 27, :first_name => "Michal", :last_name => "Hammel", :picture => "mhammel0", :title => "Biophysicist Research Scientist", :slug => "mhammel")
Scientist.create(:id => 28, :first_name => "Ming", :last_name => "Hammond", :picture => "mhammond0", :title => "Faculty Scientist", :slug => "mhammond")
Scientist.create(:id => 9, :first_name => "Jamie", :last_name => "Cate", :picture => "jcate0", :title => "Biologist Faculty Scientist", :slug => "jcate")
Scientist.create(:id => 29, :first_name => "Teresa", :last_name => "Head-Gordon", :picture => "theadgordon0", :title => "Faculty Scientist", :slug => "theadgordon")
Scientist.create(:id => 10, :first_name => "David", :last_name => "Chandler", :picture => "dchandler0", :title => "Chemist Senior Faculty Scientist", :slug => "dchandler")
Scientist.create(:id => 13, :first_name => "Dylan", :last_name => "Chivian", :picture => "dchivian0", :title => "Computational Biologist Research Scientist", :slug => "dchivian")
Scientist.create(:id => 12, :first_name => "Michelle", :last_name => "Chang", :picture => "mchang0", :title => "Biological Faculty Engineer", :slug => "mchung")
Scientist.create(:id => 16, :first_name => "Scott", :last_name => "Classen", :picture => "sclassen0", :title => "Biophysicist Research Scientist", :slug => "sclassen")
Scientist.create(:id => 17, :first_name => "Stephen", :last_name => "Cramer", :picture => "scramer0", :title => "Faculty Scientist", :slug => "scramer")
Scientist.create(:id => 30, :first_name => "Joshua", :last_name => "Heazlewood", :picture => "jheazlewood0", :title => "Biological Engineer Staff Scientist", :slug => "jheazlewood")
Scientist.create(:id => 11, :first_name => "John-Marc", :last_name => "Chandonia", :picture => "jchandonia0", :title => "Computational Biologist Research Scientist", :slug => "jmchandonia")
Scientist.create(:id => 26, :first_name => "Jay", :last_name => "Groves", :picture => "jgroves0", :title => "Chemist Faculty Scientist", :slug => "jgroves")
Scientist.create(:id => 14, :first_name => "Jhih-Wei", :last_name => "Chu", :picture => "jchu0", :title => "Biological Faculty Engineer", :slug => "jwchu")
Scientist.create(:id => 22, :first_name => "Graham", :last_name => "Fleming", :picture => "gfleming0", :title => "Chemist Senior Faculty Scientist", :slug => "gfleming")
Scientist.create(:id => 15, :first_name => "Sungwook", :last_name => "Chung", :picture => "schung0", :title => "Materials Project Scientist", :slug => "schung")
Scientist.create(:id => 18, :first_name => "Gavin", :last_name => "Crooks", :picture => "gcrooks0", :title => "Physicist Senior Scientist", :slug => "gcrooks")
Scientist.create(:id => 3, :first_name => "Thomas", :last_name => "Alber", :picture => "talber0.jpg", :title => "Biochemist Faculty Scientist", :slug => "talber")
Scientist.create(:id => 1, :first_name => "Paul", :last_name => "Adams", :picture => "padams0.jpg", :title => "Deputy Division Director", :slug => "padams")
Scientist.create(:id => 4, :first_name => "Chris", :last_name => "Anderson", :picture => "canderson0.jpg", :title => "Faculty Scientist", :slug => "canderson")
Scientist.create(:id => 23, :first_name => "Daniel", :last_name => "Fletcher", :picture => "dfletcher0.jpg", :title => "Deputy Division Director", :slug => "dfletcher")
