ScientistTitle.create(:id => 1, :title => "Faculty Scientist", :scientist_id => 23)
ScientistTitle.create(:id => 2, :title => "Faculty Scientist", :scientist_id => 3)
ScientistTitle.create(:id => 3, :title => "Chancellor's Class of '43 Professor of Molecular and Cell Biology - University of California: Berkeley", :scientist_id => 3)
ScientistTitle.create(:id => 4, :title => "Faculty Director - Henry Wheeler Center for Emerging and Neglected Diseases", :scientist_id => 3)
ScientistTitle.create(:id => 5, :title => "Senior Scientist", :scientist_id => 1)
ScientistTitle.create(:id => 6, :title => "Adjunct Professor - Department of Bioengineering - U.C. Berkeley", :scientist_id => 1)
ScientistTitle.create(:id => 7, :title => "Vice President of Technology - The Joint BioEnergy Institute", :scientist_id => 1)
ScientistTitle.create(:id => 8, :title => "ALS Division Deputy for Biosciences, Chair of the ALS Biosciences Council", :scientist_id => 1)
ScientistTitle.create(:id => 9, :title => "The SIBYLS Beamline", :scientist_id => 27)
ScientistTitle.create(:id => 10, :title => "Faculty Scientist - Center for Integrated Physiome", :scientist_id => 7)
ScientistTitle.create(:id => 11, :title => "Analysis Assistant Professor of Microbial Biology, UC Berkeley", :scientist_id => 7)
ScientistTitle.create(:id => 12, :title => "Professor - Department of Bioengineering - University of California: Berkeley", :scientist_id => 4)
ScientistTitle.create(:id => 13, :title => "Chief Scientific and Technical Officer: Joint BioEnergy Institute (JBEI)", :scientist_id => 6)
ScientistTitle.create(:id => 14, :title => "Senior Faculty Scientist Merck Professor - Department of Biochemical Engineering - University of California, Berkeley", :scientist_id => 6)
ScientistTitle.create(:id => 15, :title => "Former Division Deputy Director", :scientist_id => 24)
ScientistTitle.create(:id => 16, :title => "Leader Interface Project, Joint Center for Artificial Photosynthesis", :scientist_id => 24)
ScientistTitle.create(:id => 17, :title => "The SIBYLS Beamline", :scientist_id => 16)
ScientistTitle.create(:id => 20, :title => "Head of the Advanced Microscopies Department", :scientist_id => 8)
ScientistTitle.create(:id => 21, :title => "Faculty Scientist", :scientist_id => 8)
ScientistTitle.create(:id => 22, :title => "Professor of Biochemistry, Molecular Biology, Physics and Chemistry - University of California, Berkeley", :scientist_id => 8)
ScientistTitle.create(:id => 23, :title => "Assistant Professor - Department of Chemistry - University of California, Berkeley", :scientist_id => 25)
ScientistTitle.create(:id => 24, :title => "Former Deputy Laboratory Director", :scientist_id => 22)
ScientistTitle.create(:id => 25, :title => "Lawrence Berkeley National Laboratory Former Director, Physical Biosciences Division", :scientist_id => 22)
ScientistTitle.create(:id => 26, :title => "Former Associate Laboratory Director, Physical Sciences Division", :scientist_id => 22)
ScientistTitle.create(:id => 27, :title => "Lawrence Berkeley National Laboratory Vice Chancellor for Research", :scientist_id => 22)
ScientistTitle.create(:id => 28, :title => "Melvin Calvin Distinguished Professor of Chemistry, University of California, Berkeley", :scientist_id => 22)
ScientistTitle.create(:id => 50, :title => "JBEI Feedstocks Research Division: Director of Systems Biology", :scientist_id => 30)
ScientistTitle.create(:id => 57, :title => "Faculty Scientist", :scientist_id => 21)
ScientistTitle.create(:id => 58, :title => "Howard Hughes Investigator Professor of Biochemistry &amp; Molecular Biology, University of California, Berkeley", :scientist_id => 21)
ScientistTitle.create(:id => 92, :title => "Faculty Scientist", :scientist_id => 28)
ScientistTitle.create(:id => 93, :title => "UC Berkeley, Department of Chemistry", :scientist_id => 28)
ScientistTitle.create(:id => 104, :title => "Associate Professor of Biochemistry &amp; Molecular Biology", :scientist_id => 9)
ScientistTitle.create(:id => 105, :title => "Associate Professor of Chemistry", :scientist_id => 9)
ScientistTitle.create(:id => 106, :title => "Faculty Scientist", :scientist_id => 10)
ScientistTitle.create(:id => 107, :title => "Head, Computational and Theoretical Biology Department", :scientist_id => 10)
ScientistTitle.create(:id => 108, :title => "Professor of Chemistry, University of California, Berkeley", :scientist_id => 10)
ScientistTitle.create(:id => 109, :title => "Assistant Professor - Department of Chemistry - University of California, Berkeley", :scientist_id => 12)
ScientistTitle.create(:id => 110, :title => "Assistant Professor - Department of Biochemical Engineering - University of California, Berkeley", :scientist_id => 14)
ScientistTitle.create(:id => 111, :title => "Faculty Scientist", :scientist_id => 17)
ScientistTitle.create(:id => 112, :title => "Advanced Light Source Professor, Department of Chemistry, UC Davis", :scientist_id => 17)
ScientistTitle.create(:id => 113, :title => "Advanced Biological and Environmental X-Ray Spectroscopy (ABEX)", :scientist_id => 17)
ScientistTitle.create(:id => 114, :title => "Professor of Bioengineering, UC Berkeley", :scientist_id => 29)
ScientistTitle.create(:id => 115, :title => "Faculty Scientist - Computational and Theoretical Biology Department", :scientist_id => 29)
ScientistTitle.create(:id => 124, :title => "E.O. Lawrence Berkeley National Laboratory", :scientist_id => 5)
ScientistTitle.create(:id => 125, :title => "Professor - Department of Bioengineering - University of California, Berkeley", :scientist_id => 5)
ScientistTitle.create(:id => 126, :title => "Director, Berkeley Synthetic Biology Institute", :scientist_id => 5)
ScientistTitle.create(:id => 127, :title => "PI and Co-Director, Virtual Institute of Microbial Stress and Survival", :scientist_id => 5)
ScientistTitle.create(:id => 128, :title => "Investigator, Energy Biosciences Institute", :scientist_id => 5)
